name : Deploy to Firebase Hosting

on:
  push:
    branches:
    - main 

jobs:
  build_and_deploy:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: action/checkout@v4

      - name: Deploy to Firebase
        uses:   FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: `${{secrets.GITHUB_TOKEN}}`
          firebaseServiceAccount : `${{secrets.FIREBASE-SERVICE-ACCOUNT-KEY}}`
          channelId : live
          projectId : music-2af50

